### ISSUE TITLE
Request for Spark! Tech Resources for Sharing Decision App

### ISSUE THREAD

**Issue by MattAS** [BU-Spark/se-shared-decision-making#2] opened 2022-11-09 17:32 UTC
- Names + emails of all team members who need access:
 - Agadel: agedel@bu.edu
 - Junia: Jjanvier@bu.edu
 - Xicheng: xl88@bu.edu
 
 - Firebase Project
 - The firebase project will be used to host the website, implement firebase authentication and use firestore for user data.
 - Project due date: Dec 12

**Comment by IanSaucy** [comment] 2022-11-10 09:06
Done! https://console.firebase.google.com/project/se-shared-decision-making

**Comment by IanSaucy** [comment] 2022-11-10 09:06
once access has been confirmed. Just close this issue.

**Comment by IanSaucy** [comment] 2022-11-14 19:59
Bump

**Comment by Agedel** [comment] 2022-11-14 20:09
I was wrong. 
![image](https://user-images.githubusercontent.com/36602538/201755690-dd8b6c3a-09f6-4218-822e-a5d541e88921.png)

**Comment by IanSaucy** [comment] 2022-11-20 12:17
Give it a try now. I have created DB for you

**Comment by IanSaucy** [comment] 2022-11-28 17:08
bump

**Comment by IanSaucy** [comment] 2022-12-02 21:15
Closing due to non-contact

**Closed by IanSaucy** 2022-12-02 21:15 UTC
